networks:
  exchange-net:

services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - exchange-net

  order-api-1:
    build:
      context: .
      dockerfile: src/OrderApi/Dockerfile
    container_name: order-api-1
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Redis__Connection=redis:6379
    depends_on:
      - redis
    networks:
      - exchange-net

  order-api-2:
    build:
      context: .
      dockerfile: src/OrderApi/Dockerfile
    container_name: order-api-2
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Redis__Connection=redis:6379
    depends_on:
      - redis
    networks:
      - exchange-net

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order-api-1
      - order-api-2
    networks:
      - exchange-net

  worker-1:
    build:
      context: .
      dockerfile: src/OrderExecutionWorker/Dockerfile
    container_name: worker-1
    environment:
      - Redis__Connection=redis:6379
    depends_on:
      - redis
    networks:
      - exchange-net

  worker-2:
    build:
      context: .
      dockerfile: src/OrderFixGatewayWorker/Dockerfile
    container_name: worker-2
    environment:
      - Redis__Connection=redis:6379
    depends_on:
      - redis
    networks:
      - exchange-net
